import Vue from 'vue'
import { Button, Form, FormItem, Input, Container, Header, Main, Footer, Card, Row, Col, Image, Radio, RadioGroup, Pagination } from 'element-ui'
Vue.use(Button)
Vue.use(FormItem)
Vue.use(Form)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Image)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(Pagination)
